extraction:
  cpp:
    after_prepare: 
      - python report.py 73
  cobol:
    after_prepare: 
      - python report.py 73
  csharp:
    after_prepare: 
      - python report.py 73
  java:
    after_prepare: 
      - python report.py 73
  javascript:
    after_prepare: 
      - python report.py 73
  python:
    after_prepare: 
      - python report.py 73
